// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baejswhhkmuokqczmphy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZWpzd2hoa211b2txY3ptcGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODk4MTgsImV4cCI6MjA2MTY2NTgxOH0.sWurKyC6LsuH35gbfmeqz2r8uzOZHID8o3IUIwLFGpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);